### ISSUE TITLE
[Question] Choice of ContentResolver.openOutputStream default mode

### ISSUE THREAD

**Issue by RobbWatershed** [tom5079/DocumentFileX#2]
I've noticed you're using `"w"` as the default mode for `ContentResolver.openOutputStream`, which I've been doing myself until the moment when :
- I opened an existing file of, say 100 bytes...
- ...to update it with a new content of 91 bytes...
- ...and realized afterwards that the updated files contains 91 bytes of the new content + 9 bytes of the old content

The file was a JSON file... and it was FUBAR after that.

I then switched to `"wt"` (write-truncate) to make it more intuitive, as the most frequent use-case is updating an entire file, not selectively updating a chunk of it.

Wouldn't it be better if you did the same here ?

https://github.com/tom5079/DocumentFileX/blob/2a916db0a67406df9cf7755153ae0f02e8735ac0/library/src/main/java/xyz/quaver/io/util/SAFileXReadWrite.kt#L36

https://github.com/tom5079/DocumentFileX/blob/bc10ba3f63a3a5918005e507f23a91ce6486b9c5/library/src/main/java/xyz/quaver/io/util/DocumentUtil.kt#L272

**Comment by tom5079** [comment]
Damn, I thought it was just another weird quirk of SAF
I didn't even know the mode "wt" existed

What I did was just manually truncating the file before writing anything to the file
https://github.com/tom5079/DocumentFileX/blob/2a916db0a67406df9cf7755153ae0f02e8735ac0/library/src/main/java/xyz/quaver/io/util/SAFileXReadWrite.kt#L93

Thanks for letting me know, I'll change it right away :)
